languageCode = "en-us"
title = "Breaking Computer"
baseurl = "https://breaking.computer/"
theme = "PaperMod"
Paginate = 5

[params.rss]
includeContent = true
authorName = "John Turner"
authorEmail = "john@breaking.computer"

[params.social]
twitter = "while1malloc0"
github = "while1malloc0"
email = "while1malloc0+breakingcomputer@gmail.com"
rss = "index.xml"

[params.social.config]
platforms = ["twitter", "github", "email"]

[taxonomies]
tag = "tags"
